import type { Metadata } from "next";
import { Bug, FileLock2, KeyRound, Lock, ServerCog, Trash2 } from "lucide-react";

import {
  Callout,
  FeatureGrid,
  PageHero,
  PageShell,
  Prose,
  Section,
  StepList,
} from "@/components/PageKit";

export const metadata: Metadata = {
  title: "Security | Keyrise",
  description:
    "How Keyrise protects passport scans and personal data — encryption, retention limits, access control, and our vulnerability disclosure policy.",
};

const controls = [
  {
    icon: <Lock className="h-5 w-5" />,
    title: "Encrypted in transit and at rest",
    description:
      "TLS 1.3 everywhere, AES-256 at rest. Document blobs sit in a separate store from application metadata, with distinct key material for each.",
  },
  {
    icon: <Trash2 className="h-5 w-5" />,
    title: "Documents deleted after filing",
    description:
      "Passport and photo scans are destroyed 30 days after a visa is issued or refused. We keep the outcome, never the underlying document.",
  },
  {
    icon: <KeyRound className="h-5 w-5" />,
    title: "Least-privilege access",
    description:
      "Filing staff see only the documents for applications assigned to them, only while that application is open. Every access is logged with a reason code.",
  },
  {
    icon: <FileLock2 className="h-5 w-5" />,
    title: "No third-party document sharing",
    description:
      "Scans go to the relevant government authority and nowhere else. They are never used for model training, analytics or advertising.",
  },
  {
    icon: <ServerCog className="h-5 w-5" />,
    title: "Regional data residency",
    description:
      "Indian applicant data stays in ap-south-1. GCC data stays in me-central-1. Neither is replicated outside its region.",
  },
  {
    icon: <Bug className="h-5 w-5" />,
    title: "Independent testing",
    description:
      "Third-party penetration tests twice yearly, plus continuous automated scanning. Summary reports are available under NDA to partners.",
  },
];

const disclosureSteps = [
  {
    title: "Send it to security@keyrise.com",
    description:
      "Include the affected endpoint, reproduction steps, and what you were able to access. Encrypt with our PGP key if the finding is sensitive.",
  },
  {
    title: "We acknowledge within 24 hours",
    description:
      "A named engineer responds — not an autoresponder. If we cannot reproduce it, we will tell you what we tried.",
  },
  {
    title: "Triage within 72 hours",
    description:
      "You get a severity assessment and a target fix date. Critical findings affecting document storage are treated as an incident immediately.",
  },
  {
    title: "Fix, verify, credit",
    description:
      "We ask you to confirm the fix. With your permission we credit you publicly. Bounties are paid for anything rated high or critical.",
  },
];

export default function SecurityPage() {
  return (
    <PageShell>
      <PageHero
        eyebrow="Security"
        title="You are handing us your passport"
        description="That deserves more than a trust badge. Here is exactly what happens to your documents, who can see them, how long we keep them, and how to report it if we've got something wrong."
      />

      <Section eyebrow="Controls" title="How your data is protected">
        <FeatureGrid items={controls} columns={3} />
      </Section>

      <Section muted eyebrow="Disclosure" title="Reporting a vulnerability">
        <div className="grid grid-cols-1 gap-10 lg:grid-cols-[1.1fr_0.9fr]">
          <StepList steps={disclosureSteps} />

          <div className="space-y-4">
            <Callout tone="success" title="Safe harbour">
              We will not pursue legal action against researchers acting in good faith under
              this policy. Testing against your own account is always in scope.
            </Callout>
            <Callout tone="danger" title="Out of scope">
              Please don&apos;t test against other people&apos;s applications, run automated
              scans that degrade service for travellers, or attempt social engineering
              against our filing staff. Those affect real people mid-application.
            </Callout>
          </div>
        </div>
      </Section>

      <Section eyebrow="Detail" title="Retention, in plain terms">
        <Prose>
          <p>
            The single question we get asked most is how long we keep a passport scan. The
            answer is <strong>30 days after your application reaches a final outcome</strong>,
            whether that outcome is an approval or a refusal.
          </p>
          <h3>What is deleted</h3>
          <ul>
            <li>Passport bio-page scans and any additional passport pages you uploaded</li>
            <li>Photographs, including any generated by the Visa Photo Creator</li>
            <li>Bank statements, income tax returns and employment letters</li>
            <li>Invitation and cover letters containing third-party personal data</li>
          </ul>
          <h3>What is retained</h3>
          <ul>
            <li>The application outcome, destination, and dates — needed for the guarantee</li>
            <li>Your visa number and validity, so you can retrieve it from your profile</li>
            <li>Payment records, retained for seven years as Indian tax law requires</li>
          </ul>
          <h3>Why we keep the outcome</h3>
          <p>
            Approval and refusal outcomes are what make{" "}
            <a href="/rejection-recovery">Rejection Recovery</a> work, and they are what the
            on-time guarantee is measured against. They contain no document content — only
            the result and its timing.
          </p>
          <p>
            You can request earlier deletion at any time by writing to{" "}
            <a href="mailto:privacy@keyrise.com">privacy@keyrise.com</a>. If your application
            is still open, note that deleting documents mid-filing will end it.
          </p>
        </Prose>
      </Section>
    </PageShell>
  );
}
